spring:
  application:
    name: producer

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/teknofest}
    username: ${DB_USERNAME:teknofest}
    password: ${DB_PASSWORD:teknofest}

    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: signa
    hibernate:
      ddl-auto: none
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${NO_REPLY_EMAIL}
    password: ${NO_REPLY_EMAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: signa-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: teknofest.signa.producer.model.event.BlockEvent

server:
  port: ${PORT:9090}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

topic:
  block-bank: bank-block-topic
  block-signa: signa-block-topic

feign:
  client:
    config:
      bank-a:
        url: ${BANK_A:http://localhost:8081}
      bank-b:
        url: ${BANK_B:http://localhost:8082}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:qYrUvRZbMm1gxAVfVG8KtJPqfLf3A2qkwo0U7cqDC+HqU0ZVOz+N4VkkFqaQoxlc}
      access-token:
        expiration: ${ACCESS_TOKEN_EXPIRATION:36000000}

  frontend:
    base-url: ${FRONTEND_BASE_URL:http://localhost:5173}
